version: '3'

services:
  kcloud-storage:
    image: kcloud/storage
    build: 
      dockerfile: Dockerfile
      context: storage
    # image: openresty/openresty:1.15.8.2-4-bionic-nosse42
    # volumes:
      # - ./storage/log:/usr/local/openresty/nginx/logs
      # - ./storage/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    container_name: kcs
